#
# DigitalOcean App Platform configuration for Paperwork Service
#
name: paperwork-service
region: nyc

services:
- name: paperwork-api
  # Source configuration
  source_dir: /

  # Runtime configuration
  dockerfile_path: Dockerfile

  # Resource allocation - smallest possible size
  instance_count: 1
  instance_size_slug: basic-xxs  # 0.5 vCPU, 0.5 GB RAM - $5/month

  # HTTP configuration
  http_port: 8080

  # Health check
  health_check:
    http_path: /api/v1/health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    failure_threshold: 3
    success_threshold: 2

  # Environment variables
  envs:
  - key: ENVIRONMENT
    value: production
  - key: PORT
    value: "8080"
  - key: SUPABASE_URL
    value: "https://db.artb.art"
  - key: TEMPLATES_PATH
    value: ./templates
  - key: FONTS_PATH
    value: ./templates/fonts
  - key: BACKGROUNDS_PATH
    value: ./templates/backgrounds

# Auto-scaling (optional)
# alerts:
# - rule: CPU_UTILIZATION
#   value: 80
# - rule: MEM_UTILIZATION
#   value: 80

# Custom domains (configure after deployment)
# domains:
# - domain: paperwork.artb.art
#   type: PRIMARY
#   zone: artb.art